ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"

Text_WelcomeWantToChangeNature::
    .string "Wanna change a Pokémon's nature?$"

Text_ChangeMonNatureToWhat::
    .string "Change {STR_VAR_1}'s nature\n"
    .string "from {STR_VAR_2} to what?$"

Text_MonChangedNature::
    .string "Your {STR_VAR_1}'s nature\n"
    .string "changed to {STR_VAR_2}$"

Text_RefusedToChangeNature::
    .string "OK, feel free to ask again\n"
    .string "if you change your mind.$"
